// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db_wallet

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64            `json:"id"`
	UserID    int64            `json:"user_id"`
	Address   string           `json:"address"`
	ChainID   int32            `json:"chain_id"`
	Balance   pgtype.Numeric   `json:"balance"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID                 int64            `json:"id"`
	Email              string           `json:"email"`
	WalletHashPassword string           `json:"wallet_hash_password"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}
